# Generated by Django 4.1.1 on 2022-09-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(blank=True, default="default.png", upload_to=""),
        ),
    ]
